{
 "title": "[NODES-WIP] Main metrics",
 "time": { "from": "now-24h", "to": "now" },
 "panels": [
  {
   "title": "CPU requests by nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_status_phase{phase=\"Running\"} * on (pod) group_right kube_pod_container_resource_requests_cpu_cores) / on (node) kube_node_status_allocatable_cpu_cores{node=~\"nebula-node.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Memory requests % by Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum by (node) (kube_pod_status_phase{phase=\"Running\"} * on (pod) group_right kube_pod_container_resource_requests_memory_bytes) / on (node) kube_node_status_allocatable_memory_bytes{node=~\"nebula-node.*\"}",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "CPU used by Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (rate(container_cpu_usage_seconds_total {instance=~\"nebula-node.*\",pod_name!=\"\"} [1m]) )",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory usage (bytes) by Nodes",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (instance) (container_memory_usage_bytes{instance=~\".*node.*\",pod_name!=\"\",container=\"\"})  / on (instance) label_replace(kube_node_status_allocatable_memory_bytes,\"instance\",\"$0\",\"node\",\".*\")",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "nodeFS (ephemeral space) % by Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"nebula-node.*\"} - node_filesystem_free_bytes) / node_filesystem_size_bytes{mountpoint=\"/var\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "imageFS (docker space) % by Node",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~\"nebula-node.*\"} - node_filesystem_free_bytes) / node_filesystem_size_bytes{mountpoint=\"/var/lib/docker\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed / Evicted PODs (by Nodes)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_pod_status_phase{phase=\"Failed\"} * on (namespace, pod) group_left (node) kube_pod_info > 0) by (node)"
    }
   ]
  }
 ]
}